### PR TITLE
ci: catch compilation errors

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
**- What I did**

Removed `--quiet-pull` and added separate `docker compose build` step. Should help us catch AOT compilation errors with more logs on exactly why

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by xavierchanth — APPROVED** [review]

**Comment by xavierchanth** [comment]
I have a fix added in #265

**Comment by JeremyTubongbanua** [comment]
Merging despite test fails because trunk is currently broken with fix in #265
