### ISSUE TITLE
build (C sshnpd): build for BSD

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1192]

**Comment by xavierchanth** [comment]
I was able to start this last week, I got as far as getting a binary to run. Immediately hit a blocker with the file system as the program couldn't find the atKeys file.

**Comment by xavierchanth** [comment]
@cpswan @cconstab I don't think I am getting back to this work any time soon.

**Comment by cconstab** [comment]
@cpswan could you take the reigns?

**Comment by cpswan** [comment]
@cconstab I'll give it a go.

**Comment by cpswan** [comment]
Here's what I did to get C sshnpd running on FreeBSD 14.1:

#### as root:

```sh
pkg update && pkg upgrade
pkg install git cmake
```

#### as user:

```sh
git clone https://github.com/atsign-foundation/noports.git
cd noports/packages/c/sshnpd/
cmake -B build -S . -DBUILD_SHARED_LIBS=off -DCMAKE_C_COMPILER=clang -DCMAKE_C_FLAGS="-pthread"
cmake --build build
mkdir ~/.ssh
chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys
```

Then the usual `./build/sshnpd -a @deviceatsign -m @manageratsign -d freebsd`

**Comment by cpswan** [comment]
Also running on OPNsense 24.7

**Comment by cpswan** [comment]
Working on FreeBSD 13.4

FWIW the 13.4 binary works on 14.1, and the 14.1 binary works on 13.4. These are not things we should rely on given that libc and kernel releases for FreeBSD are aligned (and break across major releases - even if it doesn't [apparently] happen to impact the areas we use across this release pair).

**Comment by cpswan** [comment]
Not quite building on 11.3

I have CMake compiled, and I got Clang 20, but that fails to build CJSON. So trying Clang 18.1

Moving to PR94 and reducing to 2SP for final throws of that work.

**Comment by cpswan** [comment]
Clang 18.1 failed along similar lines.

I'm going to stop here rather than spending any more time on out of support builds.

The problem lies with CJSON (@JeremyTubongbanua and @XavierChanth FYI):

```log
[ 38%] Building C object _deps/cjson-build/CMakeFiles/cjson.dir/cJSON.c.o
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: '_Generic' is a C11 extension [-Werror,-Wc11-extensions]
  566 |     if (isnan(d) || isinf(d))
      |         ^
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:82:39: note: expanded from macro '__fp_type_select'
   82 | #define __fp_type_select(x, f, d, ld) _Generic((x),                     \
      |                                       ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'volatile float' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:86:14: note: expanded from macro '__fp_type_select'
   86 |     volatile float: f(x),                                               \
      |              ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'volatile double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:87:14: note: expanded from macro '__fp_type_select'
   87 |     volatile double: d(x),                                              \
      |              ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'volatile long double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:88:14: note: expanded from macro '__fp_type_select'
   88 |     volatile long double: ld(x),                                        \
      |              ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'const volatile float' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:89:20: note: expanded from macro '__fp_type_select'
   89 |     volatile const float: f(x),                                         \
      |                    ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'const volatile double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:90:20: note: expanded from macro '__fp_type_select'
   90 |     volatile const double: d(x),                                        \
      |                    ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'const volatile long double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:91:20: note: expanded from macro '__fp_type_select'
   91 |     volatile const long double: ld(x),                                  \
      |                    ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'const float' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:92:11: note: expanded from macro '__fp_type_select'
   92 |     const float: f(x),                                                  \
      |           ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'const double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:93:11: note: expanded from macro '__fp_type_select'
   93 |     const double: d(x),                                                 \
      |           ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:9: error: due to lvalue conversion of the controlling expression, association of type 'const long double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:114:2: note: expanded from macro 'isnan'
  114 |         __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
      |         ^
/usr/include/math.h:94:11: note: expanded from macro '__fp_type_select'
   94 |     const long double: ld(x))
      |           ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: '_Generic' is a C11 extension [-Werror,-Wc11-extensions]
  566 |     if (isnan(d) || isinf(d))
      |                     ^
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:82:39: note: expanded from macro '__fp_type_select'
   82 | #define __fp_type_select(x, f, d, ld) _Generic((x),                     \
      |                                       ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'volatile float' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:86:14: note: expanded from macro '__fp_type_select'
   86 |     volatile float: f(x),                                               \
      |              ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'volatile double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:87:14: note: expanded from macro '__fp_type_select'
   87 |     volatile double: d(x),                                              \
      |              ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'volatile long double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:88:14: note: expanded from macro '__fp_type_select'
   88 |     volatile long double: ld(x),                                        \
      |              ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'const volatile float' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:89:20: note: expanded from macro '__fp_type_select'
   89 |     volatile const float: f(x),                                         \
      |                    ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'const volatile double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:90:20: note: expanded from macro '__fp_type_select'
   90 |     volatile const double: d(x),                                        \
      |                    ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'const volatile long double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:91:20: note: expanded from macro '__fp_type_select'
   91 |     volatile const long double: ld(x),                                  \
      |                    ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'const float' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:92:11: note: expanded from macro '__fp_type_select'
   92 |     const float: f(x),                                                  \
      |           ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'const double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:93:11: note: expanded from macro '__fp_type_select'
   93 |     const double: d(x),                                                 \
      |           ^
/usr/home/chris/noports/packages/c/sshnpd/build/_deps/cjson-src/cJSON.c:566:21: error: due to lvalue conversion of the controlling expression, association of type 'const long double' will never be selected because it is qualified [-Werror,-Wunreachable-code-generic-assoc]
/usr/include/math.h:112:18: note: expanded from macro 'isinf'
  112 | #define isinf(x) __fp_type_select(x, __isinff, __isinf, __isinfl)
      |                  ^
/usr/include/math.h:94:11: note: expanded from macro '__fp_type_select'
   94 |     const long double: ld(x))
      |           ^
20 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/chris/noports/packages/c/sshnpd/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/chris/noports/packages/c/sshnpd/build
*** Error code 1

Stop.
make: stopped in /usr/home/chris/noports/packages/c/sshnpd/build
```

Here's the clang that I'm using:

```log
$ /usr/home/chris/llvm-project/build/bin/clang --version
clang version 18.1.8 (https://github.com/llvm/llvm-project.git 3b5b5c1ec4a3095ab096dd780e84d7ab81f3d7ff)
Target: x86_64-unknown-freebsd11.3
Thread model: posix
InstalledDir: /usr/home/chris/llvm-project/build/bin
```
 and my CMake command line:
 
 ```sh
cmake -B build -S . -DBUILD_SHARED_LIBS=off -DCMAKE_C_COMPILER="/usr/home/chris/llvm-project/build/bin/clang" -DCMAKE_C_FLAGS="-pthread"
```

Edit: Looks like this is a [known issue](https://github.com/igraph/igraph/issues/1748) on older FreeBSD with the math.h library. It's been fixed up in v13, but that probably means we can't reach onto older (unsupported) versions unless we're willing to engage in backporting patches and other messiness.
